app/controllers/tastings_controller.rb
config/routes.rb
test/controllers/tastings_controller_test.rb

Ready for Review. 
I just created the basic foundation (routes, controller with empty actions and the views) for tastings. I could not fill up the actions because the tasting model is not created yet.

Tasting show backend

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb

Hi team,
I followed the necessary steps to install pundit (added it to the Gemfile, ran the rails install command, updated the ApplicationController).
Please review!
@Tien9320 @MmeIsabelle @nafriedman

Install pundit

---

app/controllers/application_controller.rb

I missed a little typo in the Pundit setup that caused some errors I removed it now, so it should be good.

fixed pundit setup

---

app/models/tasting.rb
db/migrate/20210823214444_create_tastings.rb
db/migrate/20210823234439_change_description_input_in_tastings_to_text_area.rb
db/schema.rb
test/models/tasting_test.rb

Created tasting model and ran migration to update the schema.

Create tasting model

---

app/policies/dashboard_policy.rb
app/policies/host_policy.rb
app/policies/participation_policy.rb
app/policies/tasting_policy.rb
test/policies/dashboard_policy_test.rb
test/policies/host_policy_test.rb
test/policies/participation_policy_test.rb
test/policies/tasting_policy_test.rb

Created pundit policy files for the four models.

---

.gitignore
app/models/host.rb
db/migrate/20210824154705_create_hosts.rb
db/schema.rb
test/models/host_test.rb

Created the host model and ran a rails db migration. I didn't customize the model yet, I will do that after I create the views file.
Please review.

Create host model

---

app/models/participation.rb
app/models/tasting.rb
app/models/user.rb
db/migrate/20210824153737_create_participations.rb
test/models/participation_test.rb

Participation model added
Updated the user and tasting models to add associations

created the participation model and added associations in user and tasting

---

app/controllers/tastings_controller.rb
app/views/tastings/index.html.erb

Ready for review.
Wrote the index method in the tastings controller with proper pundit authorization. Also included basic content in the view to check that everything was working properly, which will be removed when we begin the styling phase.

Tastings index

---

app/models/category.rb
db/migrate/20210824161306_create_categories.rb
db/schema.rb
test/models/category_test.rb

category model created

---

app/controllers/tastings_controller.rb
app/policies/tasting_policy.rb
app/views/tastings/show.html.erb

Finished show method in tastings controller with proper authorization (everyone can view) and added basic content to the page to show everything is working. This will be replaced when we get to design phase of the project.

Finished show method in tastings controller 

---

app/models/categorization.rb
app/models/category.rb
app/models/tasting.rb
db/migrate/20210824162146_create_categorizations.rb
db/schema.rb
test/models/categorization_test.rb

Generated the categorization model.
Updated associations in the category and tasting models

Categorization model

---

app/models/dashboard.rb
db/migrate/20210824173651_create_dashboards.rb
test/models/dashboard_test.rb

@nafriedman please review the dashboard model

created the dashboard model with initialize method

---

app/models/host.rb
db/migrate/20210824182820_drop_hosts_table.rb
db/schema.rb
test/models/host_test.rb

Removed host model and table

---

app/models/dashboard.rb
db/migrate/20210824173651_create_dashboards.rb
db/migrate/20210824184210_drop_dashboards_table.rb
db/schema.rb
test/models/dashboard_test.rb

Removed the dashboard model and table.
Please review!

Remove dashboard model

---

app/controllers/dashboards_controller.rb
app/policies/dashboard_policy.rb
app/views/dashboards/show.html.erb
config/routes.rb
db/schema.rb

Created the show method in the dashboard controller and in the policy.
Updated the route for /dashboard instead of /dashboards

created the dashboard show action, updated the policy and the route

---

db/migrate/20210824201806_remove_user_from_tastings.rb
db/schema.rb

Removed user_id from listings.

---

app/models/tasting.rb
app/models/user.rb

Hi @MmeIsabelle ,
This is the code we just worked on together on Zoom.
Please review!

Updated models' associations.

---

db/seeds.rb

Hi Team,
I created (and tested) a basic seed file. It includes three users (one host, two vanilla users) and three tastings.
I made sure the delete_all methods are working properly and added some helpful console messages.
Please review!

Basic seed file

---

app/models/dashboard.rb
app/models/participation.rb
app/views/dashboards/show.html.erb

Added pending scope to the participation model
Created pending-participations method in the dashboard
Built a basic view to test

Daschboard class and participations methods

---

app/models/dashboard.rb
app/models/participation.rb
app/views/dashboards/show.html.erb

Added scope for approved and finished in the tasting model
Added upcoming and past method to the dashboard class
Created a basic view with links to the tastings#show

added methods and view for upcoming and past tastings

---

app/controllers/participations_controller.rb
app/controllers/tastings_controller.rb
app/policies/participation_policy.rb
app/views/tastings/index.html.erb
app/views/tastings/show.html.erb

Finished the participations create controller with proper authorization. Authorization is only granted if the person requesting participation is not the host and the person is not already a participant (pending, accepted, declined). 
When a request is sent, the app redirects to the dashboard and displays the pending request in the pending tastings section. 
The styling for the form and everything are just basic and will be changed when we get to styling.

Participations create

---

db/migrate/20210825153829_add_more_columns_to_user.rb
db/schema.rb

Ready for review.
Added address, avatar, bio and username to the user model and users table.

Add to user model

---

app/views/dashboards/show.html.erb

Added logout in dashboard

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added logo

---

app/controllers/tastings_controller.rb
app/policies/tasting_policy.rb
app/views/dashboards/show.html.erb
app/views/tastings/index.html.erb
app/views/tastings/show.html.erb

Removed the unnecessary lines.
Tested upload to and from cloudinary
Added styling
Updated the start_at lines to be consistent with the new name

cleaned the code and styled the uploaded images

---

app/models/participation.rb
app/views/tastings/show.html.erb

updated the validations in the participation model to include declined

added declined to the status validation

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/dashboards/show.html.erb
app/views/devise/registrations/new.html.erb
app/views/tastings/index.html.erb
db/seeds.rb

Added avatar link to seed
Updated tasting address to match host and to geocode properly
Added upload avatar(optional) and enter address(required) on signup
Added permissions in the application controller
Added conditions to show avatar including a default image

Update users seed and addresses

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added hero section. (Need to get rid of brown div on top. This will happen later today.)![image](https://user-images.githubusercontent.com/82684763/131366949-f6e191cd-0b84-4644-a8de-d26c542f57ae.png)
Please review.
Upcoming fixes include the following:

Finished basic skeleton for homepage.

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss

I set up fonts we use for the website, colors. All can be found under app/assets/stylesheets/config

set up colors, fonts, border radius

---

app/views/pages/home.html.erb

Fixed logo and text alignment on homepage

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_product_card.scss
app/views/tastings/index.html.erb

This is not the correct red shade. Because I created the branch before my set up core design branch was merged,
The red is gonna be different.

Styled card product

---

app/views/pages/home.html.erb

Fixed padding, centered some text.

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Fix homepage cards

---

app/views/layouts/application.html.erb

Got rid of the brown div from the home page (as discussed). Please review.

Got rid of brown div on homepage.

---

app/models/tasting.rb
app/views/tastings/index.html.erb
app/views/tastings/show.html.erb
db/seeds.rb

Created category and categorization seeds in the seedfile. Added the search by category functionality in the tastings page. Removed the search by description functionality. Added tags to the cards on the tastings page based on the categories attributed to that tasting. Styled the category display on the tastings index and tastings show pages with font-awesome icon. I also added the feature where you can search for all tastings under a certain category by clicking that category tag on a tasting card (in the index page) or on the category tag in the show page of a tasting. 
Note that this styling was just an idea and can be changed. This is just a starting point.

Add search by category

---

app/views/shared/_head_banner.html.erb

Centered logo and text on head banner.

---

app/assets/stylesheets/components/_dashboard_card.scss
app/assets/stylesheets/components/_index.scss
app/views/dashboards/show.html.erb

card in dashboard

---

app/assets/stylesheets/pages/_home.scss

Hi Team,
I made the logo bigger on the homepage (as recommended by Esteban). Please review!

Made logo bigger on home page

---

app/assets/stylesheets/components/_head_banner.scss
app/views/dashboards/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_head_banner.html.erb
app/views/tastings/index.html.erb
app/views/tastings/new.html.erb
app/views/tastings/show.html.erb

Fix banner for all pages

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/host_card.scss
app/views/tastings/show.html.erb

Styled host card in tastings show page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Hi Team,
Slight style changes include making background white, adding line on top.
Please review!

Stuck navbar to bottom

---

app/assets/stylesheets/pages/_home.scss

Changed font family, fixed homepage bug.

---

app/controllers/conversations_controller.rb
app/controllers/messages_controller.rb
app/controllers/participations_controller.rb
app/models/conversation.rb
app/models/message.rb
app/models/user.rb
app/policies/conversation_policy.rb
app/policies/message_policy.rb
app/views/conversations/index.html.erb
config/application.rb
config/routes.rb
db/migrate/20210830145952_create_messages.rb
db/schema.rb
test/controllers/conversations_controller_test.rb
test/controllers/messages_controller_test.rb
test/models/message_test.rb
test/policies/conversation_policy_test.rb
test/policies/message_policy_test.rb

Built the messaging system between users requesting to attend and hosts.
Created a conversation page where messages are accessed and new messages added to conversations
User see by default conversation with the newer message and can toggle between correspondents.
Ready for review.
No AJAX implemented yet

Add messaging

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/tastings/new.html.erb
app/views/tastings/show.html.erb

Styled the button (color only)

Styled btns

---

app/controllers/conversations_controller.rb
app/views/conversations/index.html.erb

Added conditions so the conversation page displays even when empty instead of triggering an error.

added conditions to show the empty page even if no conversatons exist

---

config/routes.rb

Fix the route changed by accident yesterday

re-nested the participation create in the tastings

---

app/controllers/messages_controller.rb
app/controllers/participations_controller.rb
app/models/notification.rb
app/models/participation.rb
app/models/user.rb
app/views/notifications/messages/_received.html.erb
app/views/notifications/participations/_request.html.erb
config/routes.rb
db/migrate/20210831144103_create_notifications.rb
db/schema.rb
test/models/notification_test.rb

First part of the notifications completed
Notifications are created for new participation request and new message.
Once merged, I will work on broadcasting the notifications

Notification table and records

---

app/controllers/tastings_controller.rb
app/models/tasting.rb
app/views/tastings/new.html.erb

Fixed bug when adding a tasting and added ability to select multiple categories through check boxes when user creates a new tasting.

Add category selection for new tasting

---

app/controllers/tastings_controller.rb

Ready for review.
Ordered the tastings on the index page from least to most distance from the current user.

order tastings by distance to current user

---

app/views/tastings/show.html.erb

Done on zoom with @nafriedman .
Please review.

Fixed show page error.

---

app/assets/stylesheets/pages/_tasting_show.scss
db/schema.rb

Show page brown div now matches index's (and other pages') div heights.

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Fix show page card padding

---

app/views/tastings/show.html.erb

Underlined host's name to make it obvious that clicking on it does something.

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Fixed font coloring.

---

app/views/tastings/show.html.erb

Got rid of icon. Hashtag suffices and looks better.

---

app/views/tastings/show.html.erb

Built backend part of calendar on tasting show page.

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Calendar on tasting show page

---

app/views/dashboards/show.html.erb

Dashboard tabs

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Added message icon to navbar

---

app/channels/notification_channel.rb
app/controllers/conversations_controller.rb
app/controllers/messages_controller.rb
app/controllers/participations_controller.rb
app/javascript/channels/notification_channel.js
app/javascript/packs/application.js
app/models/notification.rb
app/models/user.rb
app/policies/participation_policy.rb
app/views/conversations/index.html.erb
app/views/dashboards/show.html.erb
app/views/notifications/messages/_received.html.erb
app/views/notifications/participations/_request.html.erb
app/views/shared/_message_badge.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_request_badge.html.erb
test/channels/notification_channel_test.rb

Implemented the notification broadcasts for the new messages and the new request for participation.
Pieces are there and will need to be styled - badges for nav bar, badge for hosted tasting and popup notification message

Display notifications

---

app/views/tastings/index.html.erb

Replaced tag icons with hashtags for categories on index page.

---

app/models/user.rb
app/views/conversations/index.html.erb
app/views/shared/_navbar.html.erb

Fixed the conversation page not showing when no messages existed.
Ready for review

added condition to properly load and moved notification under DM in navbar

---

app/assets/stylesheets/components/_dashboard_card.scss
app/assets/stylesheets/components/_dashboard_nav.scss
app/assets/stylesheets/components/_index.scss
app/views/dashboards/show.html.erb

Styled dashboard tabs

---

app/assets/stylesheets/components/_dashboard_card.scss

Added border radius to dashboard card

---

config/cable.yml

fix config for notifications on heroku

---

app/assets/stylesheets/components/_dashboard_nav.scss
app/views/dashboards/show.html.erb

Dashboard looks nice now, please review.

Fixed dashboard styling

---

config/meta.yml

fixed file extension

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Please review. Once this is approved I can implement avatars.

Fix show pg alignment

---

app/assets/stylesheets/components/_dashboard_nav.scss

Added closing tag

---

app/views/tastings/show.html.erb

Hi Team, please review.
I need to fix alignment, but the finished page displays the right info now.

Fixed if statement for finished tasting page

---

app/assets/stylesheets/components/_dashboard_nav.scss

move notification in dashboard a little lower

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Corrected show page alignment and made avatars look better.

---

app/assets/stylesheets/pages/_tasting_show.scss

Self-explanitory. Please review!

Refactored scss to nest avatars.

---

app/views/conversations/index.html.erb

Fixed invisible button on chat page.

---

app/controllers/tastings_controller.rb
app/models/participation.rb
app/models/tasting.rb
app/views/tastings/new.html.erb

Made changes required to have host participation saved with the creation of a tasting

removed extra validation and issues with status

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_received_popup.scss
app/views/notifications/messages/_received.html.erb

I refresh the page before I can take a screenshot and now I cannot make the popup display again :(

Styled popup box

---

db/seeds.rb

Updated seeds to be more intelligent. 
Added two users, multiple tastings,  many categories and more categorizations. Made changes to seeds to make them more realistic. 
Note: I also put the seeds in hashes so I could hide the seeds to make the file easier to navigate. 
@MmeIsabelle I left some comments for you in the file for where we will need different images for tastings or avatars for users. 
This seed file does not contain any seeds for conversations and messages. I figured we can tackle that later today or tomorrow.

Seeding update

---

app/views/notifications/participations/_request.html.erb

I aaded the same styling to request notification

Added styling to request notification

---

app/models/tasting.rb
db/seeds.rb

Fixed bug by removing validation for tasting required host. Added users and added participations to the gelato tasting.

Seeding update 2

---

app/views/pages/home.html.erb

Fixed typo. Changed banh my to banh mi and now the search results are working.

fixed typo. Should be banh mi instead of banh my

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Made host avatar bigger on tasting show page.

---

app/views/tastings/index.html.erb

Added class to uploaded image

---

app/views/tastings/index.html.erb
app/views/tastings/show.html.erb

Ready for review!
Made categories in show page appear inline with space in between categories. Made categories in show which already appear inline have space in between categories.

fixed Categories display 

---

app/assets/stylesheets/pages/_conversation_index.scss
app/assets/stylesheets/pages/_index.scss
app/views/conversations/index.html.erb

some basic style for inbox

---

app/assets/stylesheets/components/_dashboard_nav.scss
app/assets/stylesheets/components/_navbar.scss
app/javascript/channels/notification_channel.js
app/views/dashboards/show.html.erb
app/views/notifications/messages/_received.html.erb
app/views/shared/_message_badge.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_request_badge.html.erb

Cleaned up the duplication in classes and condition around the badges and adjusted the style for the dashboard.
Connection works with the channel, but more work will be required to account for the 2 different notifications in the navbar so it is updating with a refresh - will be for a new branch.

fixed the connection to the channel and removed duplicate classes

---

db/seeds.rb

added images for new users and tastings, zoomed in the avatars

---

app/assets/stylesheets/pages/_conversation_index.scss
app/views/conversations/index.html.erb

fix head banner

---

app/views/tastings/index.html.erb

Got rid of line. Need to add bottom padding after km.

---

app/views/tastings/index.html.erb

Fixed bottom margin for cards.
Please review.

Added bottom margin to cards to make alignment more event

---

app/javascript/channels/notification_channel.js
app/views/conversations/index.html.erb

I added condition to user avatar in inbox/conversation page

Fix user avatar in inbox

---

app/controllers/messages_controller.rb
app/controllers/participations_controller.rb
app/javascript/channels/notification_channel.js
app/views/shared/_message_badge.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_request_badge.html.erb

Still not reacting real-time locally, but it work on heroku with redis instead of async

splitted the channel counters to respond to both types of notifications

---

app/views/conversations/index.html.erb
app/views/dashboards/show.html.erb
app/views/tastings/index.html.erb
app/views/tastings/new.html.erb

Fix head banner display on desktop

---

app/assets/stylesheets/pages/_tasting_show.scss
app/views/tastings/show.html.erb

Fixed hosting messages alignment

---

app/javascript/channels/notification_channel.js
app/views/shared/_message_badge.html.erb

Issue finally solved and badge counter updates as notification is received

solved the badge counter not showing when notification received

---

app/views/dashboards/show.html.erb

Added margin between pending and upcoming tastings.

---

app/views/conversations/index.html.erb

Fixed alignment and wording for 'no messages' message.

---

app/views/conversations/index.html.erb

Fix navbar problem in inbox

---

db/seeds.rb

deleted meg participations and changed lorenzo's address

---

app/assets/stylesheets/pages/_conversation_index.scss
app/views/conversations/index.html.erb

Change border bottom color

---

app/views/dashboards/show.html.erb

Changed all the 'at the moment' messages to match 'at this moment.'

---

app/assets/stylesheets/pages/_conversation_index.scss
app/assets/stylesheets/pages/_home.scss
app/views/conversations/index.html.erb

change unsplash url to cloudinary url

Change img url

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added some minor style changes to the home page.
Please review.

Additional homepage styling.

---

app/views/conversations/index.html.erb
app/views/tastings/show.html.erb

Hi team,
Got rid of rounded pill class from buttons.  Doesn't fit our app's styling.
Please review.

Got rid of rounded pill class from buttons. 

---

app/views/tastings/new.html.erb

Made default tasting capacity 2.

---

app/assets/stylesheets/components/_head_banner.scss
app/views/dashboards/show.html.erb

Align headbanner with body

---

app/views/dashboards/show.html.erb

As per team request.
Please review.

Removed message if user has no upcoming/pending tastings.

---

app/views/dashboards/show.html.erb

Added working if statement for empty pending and upcoming tastings.

---

app/assets/stylesheets/components/_dashboard_card.scss
app/views/dashboards/show.html.erb
app/views/participations/_card.html.erb

Dashboard datetime

---

app/assets/stylesheets/components/_received_popup.scss
app/views/notifications/messages/_received.html.erb

Longer alert time

---

app/views/notifications/messages/_received.html.erb

Added avatar to message request notification.

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Made home page tagline bigger. Looks more visually appealing.

---

app/views/pages/home.html.erb
db/seeds.rb

This should improve the loading time of the page
@nafriedman if you want to review and test, this would be great!

added width in images for tastings in seed and on the card on home page

---

app/views/notifications/messages/_received.html.erb

Fixed the issue with conversation page not opening on the user when clicking on the alert

changed user in the link to open the correct page

---

app/assets/stylesheets/pages/_home.scss
app/views/dashboards/show.html.erb
app/views/participations/_card.html.erb

Aligned date time and change color

---

db/seeds.rb

Added local category to categories.

added local category

---

app/assets/stylesheets/pages/_home.scss

reduced cover image size

---

db/seeds.rb

@dylancherry98  Please review.

changed date so tasting would appear

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

reduced images size again to improve loading
